### PR TITLE
Add config to stop syncing node when reaching particular block

### PR DESCRIPTION
**Pull request by vgulkevic**
- Add config to stop syncing node when reaching particular block
-Cleanup dead code

### CODE REVIEW

**Comment by vgulkevic** [comment]
Param: maxblockheight
after reaching this block, the node will stop processing any incoming messages

**Review by CryptoCoderz — CHANGES_REQUESTED** [review]
Please leave the Test Fork functionality. This is required for running a testnet of the main operating parameters prior to having an official update make a big change. (Test large network changes)

**Comment by vgulkevic** [comment]
Put it back!

**Comment by CryptoCoderz** [comment]
> Put it back!

Thank you bud, reviewing now on my phone.

**Review by CryptoCoderz — APPROVED** [review]
Looks great. Thank you very much for revising it!

**Pull request merged**
