### PR TITLE
Update leveldb, update docs

### PR DESCRIPTION
**Pull request by vgulkevic**
Updated the version of leveldb to the latest. Also updated docs and deleted the stale ones. However, I am using MacOS so I haven't tested this on Windows and haven't updated the docs for Windows

### CODE REVIEW

**Review by CryptoCoderz — COMMENTED** [review]
Will attempt a build with this prior to merge. Typically libmemenv.a is a required file. Just want to double check this.

**Review by CryptoCoderz — COMMENTED** [review]
Deleting the makefiles is unacceptable. Please re-approach your changes with a fresh pull request.

**Comment by CryptoCoderz** [comment]
Denied

**Comment by vgulkevic** [comment]
sorry why do you need the stale makefiles? There is DigitalNote.pro file that you can compile with:

   ```
   qmake RELEASE=1 USE_UPNP=1 USE_QRCODE=1 DigitalNote.pro
   make


  ```

**Comment by CryptoCoderz** [comment]
It is needed to build native daemons for users that do not wish to have Qt or wish to build without having the Qt IDE

**Comment by CryptoCoderz** [comment]
for example, makefile.unix is used all the time to build daemon on Ubuntu servers. I use it all the time.

**Comment by CryptoCoderz** [comment]
This is also used by exchanges.

**Comment by vgulkevic** [comment]
I think it would be nice to move everything into .pro instead of trying to maintain 5+ different files

**Comment by CryptoCoderz** [comment]
this isn't something that service providers like Bittrex will tolerate. They require a makefile and will not use Qt. Many users and providers using server oriented OS's will refuse to do so.

**Review by CryptoCoderz — CHANGES_REQUESTED** [review]
Please leave makefiles as per our discussion, excellent work by the way.

**Comment by vgulkevic** [comment]
:+1: Will come back to this PR after the airdrop. Don't want to mess things up

**Comment by 2a5A1Ghu1** [comment]
Wouldn't it be more advantages to just move to an autotools build system? Just my two satoshis on if you're thinking about changing the build system.

**Comment by CryptoCoderz** [comment]
> Wouldn't it be more advantages to just move to an autotools build system? Just my two satoshis on if you're thinking about changing the build system.

This has been suggested a few times before, we are not apposed to having an autotools setup for the codebase but we will not replace the ability to manually compile natively on each OS via makefile and Qt .pro files. Autotools is a gigantic mess and building the current method is faster and cleaner not to mention not reliant on links that may or may not go down. 

So again adding such a functionality would be great to provide our users with more options but not replace current methods.

**Comment by CryptoCoderz** [comment]
> 👍 Will come back to this PR after the airdrop. Don't want to mess things up

No worries 😊 thanks for the hard work you do bud.

**Comment by 2a5A1Ghu1** [comment]
> > Wouldn't it be more advantages to just move to an autotools build system? Just my two satoshis on if you're thinking about changing the build system.
> 
> This has been suggested a few times before, we are not apposed to having an autotools setup for the codebase but we will not replace the ability to manually compile natively on each OS via makefile and Qt .pro files. Autotools is a gigantic mess and building the current method is faster and cleaner not to mention not reliant on links that may or may not go down.
> 
> So again adding such a functionality would be great to provide our users with more options but not replace current methods.

Well using the current build system I am unable to natively build in macOS 10.15.6 with current brew installs, even with my own build of openssl 1.0.1, with symlinks, and you can natively build with autotools on mac and linux, bitcoin has added native windows building as well, personally I find autotool easier to build with, but ok :)

**Comment by CryptoCoderz** [comment]
Please use main repository https://github.com/DigitalNoteXDN/DigitalNote-2 for all further pull requests as per request.

**Pull request closed without merging**
